// Import our database connection so we can read/write data
const db = require('../config/db');

// Import our distance calculation utility
const { calculateDistance } = require('../utils/distance');

// ==========================================
// ADD SCHOOL API
// ==========================================
// This function runs when someone makes a POST request to /addSchool
const addSchool = async (req, res) => {
    try {
        // req.body contains the JSON data the user sent us.
        // We use "destructuring" to pull out the exact fields we expect.
        const { name, address, latitude, longitude } = req.body;

        // 1. DATA VALIDATION
        // We must check if the user sent us correct data before trying to save it.
        // If the data is bad, we stop here and return a 400 Bad Request error.
        
        if (!name || typeof name !== 'string' || name.trim() === '') {
            return res.status(400).json({ success: false, message: 'Name is required and must be a valid string' });
        }
        if (!address || typeof address !== 'string' || address.trim() === '') {
            return res.status(400).json({ success: false, message: 'Address is required and must be a valid string' });
        }
        if (latitude === undefined || isNaN(parseFloat(latitude))) {
            return res.status(400).json({ success: false, message: 'Latitude is required and must be a valid number' });
        }
        if (longitude === undefined || isNaN(parseFloat(longitude))) {
            return res.status(400).json({ success: false, message: 'Longitude is required and must be a valid number' });
        }

        // Convert coordinates to floating-point numbers to be safe
        const lat = parseFloat(latitude);
        const lon = parseFloat(longitude);

        // 2. DATABASE INSERTION
        // We use ? as placeholders to prevent SQL injection (a common security hack).
        const query = 'INSERT INTO schools (name, address, latitude, longitude) VALUES (?, ?, ?, ?)';
        
        // Execute the query, replacing the ? with our actual data
        const [result] = await db.query(query, [name.trim(), address.trim(), lat, lon]);

        // 3. SEND SUCCESS RESPONSE
        // 201 means "Created successfully"
        res.status(201).json({
            success: true,
            message: 'School added successfully',
            data: {
                id: result.insertId, // The ID automatically generated by MySQL
                name,
                address,
                latitude: lat,
                longitude: lon
            }
        });
    } catch (error) {
        // If anything goes wrong (like a database failure), catch the error here
        console.error('Error adding school:', error);
        res.status(500).json({ success: false, message: 'Internal server error while adding school' });
    }
};

// ==========================================
// LIST SCHOOLS API
// ==========================================
// This function runs when someone makes a GET request to /listSchools
const listSchools = async (req, res) => {
    try {
        // For GET requests, data usually comes in the URL query string
        // Example: /listSchools?latitude=123&longitude=456
        const { latitude, longitude } = req.query;

        // 1. DATA VALIDATION
        if (latitude === undefined || isNaN(parseFloat(latitude))) {
            return res.status(400).json({ success: false, message: 'Valid latitude query parameter is required' });
        }
        if (longitude === undefined || isNaN(parseFloat(longitude))) {
            return res.status(400).json({ success: false, message: 'Valid longitude query parameter is required' });
        }

        const userLat = parseFloat(latitude);
        const userLon = parseFloat(longitude);

        // 2. FETCH ALL SCHOOLS
        // We get every single school from the database
        const [schools] = await db.query('SELECT * FROM schools');

        // 3. CALCULATE DISTANCE FOR EACH SCHOOL
        // .map() creates a new array by running a function on every item in the original array
        const schoolsWithDistance = schools.map(school => {
            // Calculate how far the user is from this specific school
            const distance = calculateDistance(userLat, userLon, school.latitude, school.longitude);
            
            // Return a new object with all the school info PLUS the distance
            return {
                ...school, // Copy existing school data
                distance: parseFloat(distance.toFixed(2)) // Keep it as a raw number for math sorting
            };
        });

        // 4. SORT BY DISTANCE
        // .sort() compares items. a - b sorts them from lowest to highest (nearest first)
        schoolsWithDistance.sort((a, b) => a.distance - b.distance);

        // 5. FORMAT THE OUTPUT
        // Change the raw number into a pretty string like "10.50 km" for the user
        const formattedSchools = schoolsWithDistance.map(school => ({
            ...school,
            distance: `${school.distance.toFixed(2)} km`
        }));

        // 6. SEND SUCCESS RESPONSE
        // 200 means "OK"
        res.status(200).json({
            success: true,
            count: formattedSchools.length,
            data: formattedSchools
        });

    } catch (error) {
        console.error('Error listing schools:', error);
        res.status(500).json({ success: false, message: 'Internal server error while listing schools' });
    }
};

// Export the functions so schoolRoutes.js can use them
module.exports = {
    addSchool,
    listSchools
};
